name: road_quality_tracker
description: "Road Quality Tracker is a Flutter-based mobile app that detects and records road surface quality using your phone’s sensors (e.g., accelerometer and GPS). It logs vibration data, maps the route in real time, and allows users to analyze road conditions for later review."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+7

environment:
  sdk: ^3.7.2
  flutter: 3.29.3

dependencies:
  flutter:
    sdk: flutter
  location: ^8.0.0
  sensors_plus: ^6.1.1

  cupertino_icons: ^1.0.8
  provider: ^6.1.5
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.1
  intl: ^0.20.2
  vector_math: ^2.1.4

  flutter_background_service: ^5.1.0
  flutter_background_service_ios: ^5.0.3
  flutter_background_service_android: ^6.3.0
  permission_handler: ^12.0.0+1
  flutter_local_notifications: ^19.3.0

  http: ^1.4.0
  flutter_secure_storage: ^9.0.0
  file_picker: ^10.2.0
  package_info_plus: ^8.3.0
  open_file: ^3.5.10
  android_intent_plus: ^4.0.3
  share_plus: ^11.0.0
  device_info_plus: ^11.5.0
  crypto: ^3.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^5.0.0
  hive_generator: ^2.0.1
  build_runner: ^2.4.6
  flutter_launcher_icons: ^0.14.4 # or latest

flutter_icons:
  android: true
  ios: false
  image_path_android: "assets/icon/app_icon.png"
  adaptive_icon_foreground: "assets/icon/app_icon.png"
  adaptive_icon_background: "#45608f"  


flutter:
  uses-material-design: true

