name: 'Android App'

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  multi:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '17'
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.29.3'
      - run: git config --global url."https://".insteadOf git:// # allows dependency downloads without gpg
      - run: flutter pub get
      - name: "Prepare environment"
        run: |
          echo '${{ secrets.KEYSTORE }}' | base64 -d > android/app/MoLeWa-release-key.jks
          echo '${{ secrets.PROPERTIES }}' > android/key.properties
          v=$(grep -Po 'version: \K.*' pubspec.yaml)
          echo "VERSION=$v" >> .env
          echo "VERSION=$v" >> $GITHUB_ENV
      - name: "Build app"
        run: flutter build apk --no-tree-shake-icons
      - name: "Create release"
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: ${{ env.VERSION }}
          prerelease: false
          title: ${{ env.VERSION }}
          files: |
            LICENSE
            build/app/outputs/flutter-apk/app-release.apk